### ISSUE TITLE
we are getting following error on Android 

### ISSUE THREAD

**Issue by AmirDoreh** [up-inside/react-native-admost#1]
![photo_2021-08-31_19-29-31](https://user-images.githubusercontent.com/45465967/131540886-9a593420-746b-487a-ac5b-d98fe1914f3c.jpg)

which is coming from `AdMost.java` .

Also it is not showing ad on some devices.

**Comment by srfaytkn** [comment]
Hey @AmirDoreh, 

What is the crash rate and can you share more information about devices that don't show ads?

**Comment by AmirDoreh** [comment]
The device is Redmi Note 8 Android version 10QKQ MIUI version 12.0.6.0 @srfaytkn 
also some of the Android users has the same problem , i think it can be from Admost sdk
